# Site settings
title: Grace #website title
description: > # this means to ignore newlines until "baseurl:"
  Grace
url: #https://grace-dxj.github.io/Grace-dxj/
baseurl: # the sub-path of your site, e.g. /blog/

disqus_shortname: Grace # leave empty if you don't want comments
google_analytics: false #if set to "true" modify the google_analytycs.html, set to false otherwise

# Links settings
links:
  - name:         Resume
    url:         https://github.com/Grace-dxj/Vitae
  - name:         Weibo
    url:          https://weibo.com/3556178997/profile?rightmod=1&wvr=6&mod=personinfo&is_all=1
    external:     false
  - name:         Email
    url:         www.2667878530@qq.com
    external:     false
    external:     false
  - name:         GitHub
    url:          https://github.com/Grace-dxj
    external:     true

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]